# Generated by Django 3.0.5 on 2020-04-09 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FileUpload',
            new_name='FileModel',
        ),
    ]
