# Generated by Django 3.0.5 on 2020-04-10 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dropbox', '0002_auto_20200409_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='filemodel',
            name='size',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
